# Generated by Django 5.2.17 on 2026-09-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('nombre', 'telefono', 'email')},
        ),
    ]
