# Generated by Django 5.2.17 on 2026-09-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operativo', '0002_orden_origen_tiempo_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('SUGERENCIA', 'Sugerencia'), ('DENUNCIA', 'Denuncia')], default='SUGERENCIA', max_length=12)),
                ('mensaje', models.TextField(max_length=1000)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('contacto', models.CharField(blank=True, help_text='Email o teléfono, si quiere respuesta.', max_length=150)),
                ('revisada', models.BooleanField(default=False)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retroalimentaciones', to='operativo.mesa')),
            ],
            options={
                'verbose_name': 'retroalimentación',
                'verbose_name_plural': 'retroalimentaciones',
                'ordering': ['revisada', '-creado_en'],
            },
        ),
    ]
