# Generated by Django 5.2.17 on 2026-09-08 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad_medida', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('item_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_recetas', to='inventario.iteminventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='catalogo.producto')),
            ],
            options={
                'ordering': ['producto__nombre'],
                'unique_together': {('producto', 'item_inventario')},
            },
        ),
    ]
